<<<<<<< HEAD
version: "3.8"

services:
  database:
    image: mysql
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=world
    ports:
      - 3360:3360

  webserver:
    build: ./src
    depends_on:
      - database
    restart: on-failure
    environment:
      - DATABASE_HOST=database
    ports:
      - 3000:3000
=======
version: "3.8"

services:
  database:
    image: mysql
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=world
    ports:
      - 3360:3360

  webserver:
    build: ./src
    depends_on:
      - database
    restart: on-failure
    environment:
      - DATABASE_HOST=database
    ports:
      - 3000:3000
>>>>>>> af63ccd556d80a2c490e977672e3c76f7f9c2d20
